apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-ui
  namespace: jalapeno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-ui
  template:
    metadata:
      labels:
        app: network-ui
    spec:
      containers:
      - name: api
        image: network-ui-api:latest
        args:
          - --v
          - "5"
          - --database-server
          - "http://arangodb:8529"
          - --database-name
          - "jalapeno"
        volumeMounts:
          - name: credentials
            mountPath: /credentials
        ports:
        - containerPort: 8000
      - name: frontend
        image: network-ui-frontend:latest
        ports:
        - containerPort: 80
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno 